travis:
  secure:
    BINSTAR_TOKEN: JMWx6wRXX4sfew0tOxiEMKEjkY+GJcwTKTPMbOC9jRHYUjRV9+mnGfWOxtAfzTFUK2ATUJSl2OGwmYoPPcb7wcaVx2YKFmw8iabJIWfLg1w3jNJrYonQC/3+r9jt/ux4/dn8XMQECy6j2mKGR1TAgV0Sv4bj6zLn+wvKJhOR6zTB/kBZ+0Lw9Z9PZ8gaTCiMFlVhSuXdgApptn81Ub8jxXyiD9lubrbcHfLuCC2l4qJCXBYmoR6A7JFuZn5fvdhrFi10+KRidJTtAgDjMDvznjFgXZhaKOlDtjB24jmBt69yz4hRav8V9sKV8WnRgGZxBFLG1rwPnzdBRQPlF13tyzHnOJcyQCFs5Iz8bK6DP7V0mhtMSm844g6YM+0hg2RuseYL5MIQ5CTz6LvisO6LruHvDkffQcYtE09fRrj4Bz0aUmS+NMeHDs8EHXklwEyI3Vquvds4a7TYStn4Fk/lQn8l0NUGMYkgVyPX3DZQjCpgPGfDnLcpsfDNjZRalRvm0c/AKaJFy8QlGq2ZMrRdip+nd2kPJUDN6LJcW8UR6kuxPt2nXauSOpCSAwAmywFebKzovyOWI98dzGqC6h6tqUNVVZfwn6QDpM2wdDqkgshDk43clvozmHSPVYmqVHKWdxnqsWqvLdu7zwdtpTnwIm85jMLemFe6ozKEUZUvLxw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
