travis:
  secure:
    BINSTAR_TOKEN: FgW+2Tdnu2HTCXLO27XVEfeuDFFecLLdLMbjhqs3rlVf6Ov4NQXFFUMIvBQ2xxu5hsMQywfLYaHgQynuw6kR7ueI7DxILdYixuh2pyfnt/GxTq+5CXg2xQ3QafTHd+H06tGLUBovizYp3ZXUvWoOELP6M4UhS+hyt5k7e8anJlbIUFkP5rJJvRetfObQD0knDCLwcIGcCNduF5RKtAQ/G7tgXEUHwAP4Ah05vzn5JvB9JT+9njGYXUISMUVn6AUPfuU5vGFvqT+7RV6rGQW/34TnJ3FCoFKLMBCYu2py/sfhEzA8xGqB3JkPHVqwsbEz3fRwwzhW5OZ6OrR9rN8CiG8wE7r8EuIjY+Fk96ESm6/yMijZzYZceTBKWQ8Rs8m9qMOuRBJMg6TgBFHiSJebc4SnDqqo8hWDVyNJPFA7EaIt55K+kmJrPulDwRz5Act7ULQ9s8PttmpDCGtyKHpdZ5uVwfCCx9A+cYVsQqw325k0eLWk6mWalc2FjhkjqxcvykR28ZEZzB/fapXzMuAMHJIeBnxBxnta7Nx4lK0FbjuGYMeSIsqO4sClv3IalwH5flBtVdqi0BwcRXBP3UUFIYAIp9Y7rmA4YgjLvEdytGV2HK6eTZ3Lpkeq/zLpxPvFmJDM3paRtpN7bVTdw6BKpuQTRIQD3YBZ3Um083oncLo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
