travis:
  secure:
    BINSTAR_TOKEN: Lsnzxf1EhK21zQ08PcPdZAnamUG13Cq1r5LuBaRklAbKRJFREUFX+MK9FeYN0E149D/w5OrMqer8EnfREL16nxezmSU2QEoV50ujG/mcQu0beBDvdSfTDfUIp1w29Fnd6jvIPx+5SM88e4O0+uuMGGK0YLRY1VVrH2YsTnSS1BWvuwF67mTpmivnJoy2HMy/6anhGN9yUntr6Ps6/f/+3PSS/ExYPHjjwO8auCUna1/9TrgHXEJID95Q3HSpVPXe+nHgPh2wk/RgP78ZRFmixrJUTT/IFhReJZm4D9tkwsY3KbFIjnhxiJZByRSFRWtCHJ1hWvt69rr2+QhP1W2oSPzbA9tX1E/G9H5YHgpfQ5ZubqAfXL39C9V/GCOGvVYaaP5RGPxmAFRJQKLMg9XrLeLPuPeLxJCP0NsyOJoxoce5AcIkmxNNJ2QkMlvcPmzBxofFJw/+6EIbybyFVtjJEmNXCWJNYO0Za+QUZ2n5Fn8b7nbt7ldFDjsrKNNlJZqZ0A3sKP/0ppTjExX6ctxcRzduxZNTpwfFNIWlbKxU/bEiMP3VHnrlmmGuD+18cusBhBko+PhLK94wOw6xqYnDtSel5PE7bhDWx18ELa+1Xjf1lkeVfCwYiqooia0keNvdlZ7qjSZHfD9l0qCYObeQb4qlymcVY5x5yRgMer/d8j8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
